theme: jekyll-theme-slate
title: Ecossistema do CTE/ZL/IFRN
description: Visão de como este ecossistema foi arquitetado para que você possa tentar se inspirar e reproduzir em seu ambiente a fim de melhorar a oferta de serviço AVA a sua comunidade acadêmica.
google_analytics: G-J58HZ8PV04
